source("1 - clean.R")
library(sjPlot)
library(texreg)
library(margins)
library(lme4)
contrasts(sudi$yod)  <- contr.treatment(levels(sudi$yod), base=which(levels(sudi$yod) == "2014"))
contrasts(sudi$dhb)  <- contr.treatment(levels(sudi$dhb), base=which(levels(sudi$dhb) == "Southern"))
contrasts(sudi$eth)  <- contr.treatment(levels(sudi$eth), base=which(levels(sudi$eth) == "European or other"))
contrasts(sudi$sex)  <- contr.treatment(levels(sudi$sex), base=which(levels(sudi$sex) == "F"))
contrasts(sudi$bw)   <- contr.treatment(levels(sudi$bw), base=which(levels(sudi$bw) == "2500-2999"))
contrasts(sudi$dep)   <- contr.treatment(levels(sudi$dep), base=which(levels(sudi$dep) == "01-08"))
s1   <- glm(sudi ~ yod + bw + dhb + dep + sex + eth, data = sudi, family = "binomial" )
sjp.glm(s1)
screenreg(s1, single.row = T)
