library(sjPlot)
library(texreg)
library(margins)
library(lme4)
contrasts(sudit$yod)  <- contr.treatment(levels(sudit$yod), base=which(levels(sudit$yod) == "2014"))
contrasts(sudit$dhb)  <- contr.treatment(levels(sudit$dhb), base=which(levels(sudit$dhb) == "Southern"))
contrasts(sudit$eth)  <- contr.treatment(levels(sudit$eth), base=which(levels(sudit$eth) == "European_or_other"))
contrasts(sudit$sex)  <- contr.treatment(levels(sudit$sex), base=which(levels(sudit$sex) == "F"))
contrasts(sudit$bw)   <- contr.treatment(levels(sudit$bw), base=which(levels(sudit$bw) == "over4500"))
contrasts(sudit$dep)   <- contr.treatment(levels(sudit$dep), base=which(levels(sudit$dep) == "01-08"))
s1   <- glm(sudi ~ yod + bw + dhb + dep + sex + eth, data = sudit, family = "binomial" )
sjp.glm(s1)
screenreg(s2, single.row = T)

